---
- name: backup cisco IOS with date stamp
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: show run
      ios_command:
        # authorize: yes
        commands:
          - show run

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: save output to a file
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}_running-config_{{ timestamp.stdout }}.txt"
